version: '3'
services:
  main:
    build: .
    restart: "no"
    ports:
      - 5000:5000
    networks:
      - internal
  redis:
    image: "redis:alpine"
    networks:
      - internal
    ports:
      - 6379:6379
    environment:
      - TTL=86400

networks:
  internal:
